services:
  sandbox-base:
    build:
      context: .
      dockerfile: Dockerfile
    image: sandbox:latest
    stdin_open: true
    tty: true
    security_opt:
      - seccomp:unconfined
    environment:
      - TERM=xterm-256color
    env_file:
      - .env
    volumes:
      - ${HOME}/.ssh:/home/matteo/.ssh:ro
      - ${HOME}/.gnupg:/home/matteo/.gnupg:ro
